---
# tasks file for 2do_parcial
- debug:
    msg: "Tareas del 2do Parcial"
- name: "Crear directorios en /tmp/2do_parcial/"
  file:
    path: "/tmp/2do_parcial/{{ item }}"
    state: directory
    mode: '0775'
    recurse: yes
  with_items: 
    - "alumno"
    - "equipo"

- name: "Agrego archivo desde template"
  template:
    src: template_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: "Agrego archivo desde template"
  template:
    src: template_equipo.j2
    dest:  /tmp/2do_parcial/equipo/datos_equipo.txt

- name: "add NOPASSWD in sudores for group 2PSupervisores"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%2PSupervisores=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
